# Generated by Django 5.2.7 on 2025-10-21 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
